stages:
  - build
  - test
  - deploy
  - cleanup

.windows_32: &win32
  tags:
    - windows
    - x86
  before_script:
    - "echo off"
    - "set"
    - 'call "%VS140COMNTOOLS%\..\..\VC\bin\vcvars32.bat"'
      #   - 'call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\vcvars32.bat"'
    - set EXT_LIBS=C:\external_libs\x86
      #- set CMAKE_GENERATOR=NMake Makefiles
    - set CMAKE_GENERATOR=Visual Studio 14 2015
    - set INSTALL_DIR=C:/install32
    - set NETGENDIR=C:\install32\bin
    - set PYTHONPATH=C:\install32\lib\site-packages
    - set PYTHON_LIB=C:/Python3.5_32/libs/python35.lib
    - set PYTHON_CONFIG=-DPYTHON_LIBRARY=C:/Python3.5_32/libs/python35.lib -DPYTHON_INCLUDE_DIR=C:/Python3.5_32/include -DPYTHON_INCLUDE_DIR2=C:/Python3.5_32/include 

.windows_64: &win64
  tags:
    - windows
    - x64
  before_script:
    - "echo off"
    - "set"
    - 'call "%VS140COMNTOOLS%\..\..\VC\bin\amd64\vcvars64.bat"'
      #  - 'call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\vcvars64.bat"'
    - set EXT_LIBS=C:\external_libs\x64
      #- set CMAKE_GENERATOR=NMake Makefiles
    - set CMAKE_GENERATOR=Visual Studio 14 2015 Win64
    - set INSTALL_DIR=C:/install64
    - set NETGENDIR=C:\install64\bin
    - set PYTHONPATH=C:\install64\lib\site-packages
    - set PYTHON_LIB=C:/Python3.5/libs/python35.lib
    - set PYTHON_CONFIG=-DPYTHON_LIBRARY=C:/Python3.5/libs/python35.lib

.template_build_win: &build_win
  stage: build
  script:
    - if not exist build MKDIR build
    - cd build
    - DEL CMakeCache.txt
    - RD /S CMakeFiles
    - >-
        cmake ..\
        -DADDITIONAL_PATHS="%EXT_LIBS%\ext_libs"
        %PYTHON_CONFIG%
        -G"%CMAKE_GENERATOR%"
        -DINSTALL_DIR="%INSTALL_DIR%"
        -DUSE_MKL=ON
        -DMKL_STATIC=ON
        -DCMAKE_CXX_FLAGS_RELEASE="/W0"
    - cmake --build . --target INSTALL --config Release

.template_test_win: &test_win
  stage: test
  script:
    - cd build
    - ctest -C Release -V

build_win32:
  <<: *win32
  <<: *build_win
  cache:
    paths:
      - build/
    key: "ngsolve_win32"

build_win64:
  <<: *win64
  <<: *build_win
  cache:
    paths:
      - build/
    key: "ngsolve_win64"

# skip since we have no machine with 32 bits
.test_win32:
  <<: *win32
  <<: *test_win
  cache:
    paths:
      - build/
    key: "ngsolve_win32"

test_win64:
  <<: *win64
  <<: *test_win
  cache:
    paths:
      - build/
    key: "ngsolve_win64"

build_ubuntu_1604:
  stage: build
  tags:
    - linux
  before_script:
    - docker info
  script:
    - rm -f ngsolve_16.04.id
    - docker run -v /opt/intel:/opt/intel --cidfile ngsolve_16.04.id -e CCACHE_DIR=/ccache -v /mnt/ccache:/ccache netgen_installed:16.04 bash /root/build_ngsolve.sh
    - docker commit `cat ngsolve_16.04.id` ngsolve_installed:16.04

test_ubuntu_1604:
  stage: test
  tags:
    - linux
  script:
    - docker run -v /opt/intel:/opt/intel -e LD_LIBRARY_PATH=/opt/intel/mkl/lib/intel64 ngsolve_installed:16.04 bash -c 'source /etc/profile.d/netgen_profile.sh && cd /root/build/ngsolve && make test ARGS="-V"'


linux_cleanup:
  stage: cleanup
  tags:
    - linux
  script:
    # remove old docker images
    docker images --no-trunc -aqf "dangling=true" | xargs docker rmi -f
  when: always
